In [2]:
from scipy.io import loadmat

In [3]:
train_data="data/lbp_WDRef.mat"
train_label="data/id_WDRef.mat"

In [4]:
data  = loadmat(train_data)['lbp_WDRef']
label = loadmat(train_label)['id_WDRef']

In [5]:
data.shape, type(data),label.shape

((71846, 5900), numpy.ndarray, (71846, 1))

In [6]:
label[45:55]

array([[2],
       [2],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3]], dtype=uint16)

In [15]:
max([max(each) for each in data])

100

In [27]:
import numpy as np
d = np.array([[1,2],[1,1],[1,0]])
d,d.shape

(array([[1, 2],
        [1, 1],
        [1, 0]]), (3, 2))

In [30]:
t = np.repeat(np.sum(d, 1), d.shape[1]).reshape(d.shape[0], d.shape[1])
t

array([[2.41421356, 2.41421356],
       [2.        , 2.        ],
       [1.        , 1.        ]])

In [31]:
np.divide(d, t)

array([[0.41421356, 0.58578644],
       [0.5       , 0.5       ],
       [1.        , 0.        ]])

In [29]:
d = np.sqrt(d)
d

array([[1.        , 1.41421356],
       [1.        , 1.        ],
       [1.        , 0.        ]])